Title: LDAP: Fixed exception when syncing groups using configurations from previous versions
Level: 1
Component: multisite
Class: fix
Compatible: compat
State: unknown
Version: 1.2.7i4
Date: 1444981575

This fixes the exception "TypeError: 'LDAPUserConnector' object has not attribute '__getitem__'.
